---
language: go
go:
  - release
  - 1.4
  - 1.3
  - 1.2

sudo: required
dist: trusty

env:
  - TEST_MYSQL_HOST='localhost' TEST_MYSQL_USER='root' TEST_MYSQL_PASSWORD='' TEST_PGSQL_HOST='localhost' TEST_PGSQL_USER='postgres' TEST_PGSQL_PASSWORD=''

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
      - librrd-dev

notifications:
  email:
    - dev@facette.io

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6
  - mysql -u root -e 'create database facette;'
  - psql -U postgres -c 'create database facette;'

script:
  - make test

# vim: ts=2 sw=2 et
