---
language: go
go:
  - release
  - 1.4
  - 1.3
  - 1.2

services:
  - mysql
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq librrd-dev

before_script:
  - mysql -e 'create database facette;'
  - mysql -e "grant all privileges on facette.* to 'facette'@'%' identified by 'facette';"
  - psql -c "create user facette with password 'facette';" -U postgres
  - psql -c 'create database facette owner facette;' -U postgres

script:
  - make test

notifications:
  email:
    - dev@facette.io

# vim: ts=2 sw=2 et
